### ISSUE TITLE
Keluhan fitur game

### ISSUE THREAD

**Issue by rafiadlifairuz** [XM4ZE/XMYULA-MD#2]
Teruntuk developer bot ini saya ingin melaporkan bahwa fitur game tidak dapat digunakan karena untuk menyelesaikan tugas dri bot,bot tidak merespon seperti Benar! Atau Salah!,tolong di perbaiki 
Sekian terimakasih 🙏🏻
RAF#1
This user Your Bot Sc

**Comment by XM4ZE** [comment]
Sudah di perbaiki ya
