### ISSUE TITLE
Keluhan fitur auto welcome 

### ISSUE THREAD

**Issue by rafiadlifairuz** [XM4ZE/XMYULA-MD#4]
Teruntuk developer bot ini saya ingin melaporkan bahwa fitur welcome tidak memunculkan thumbnail atau foto profil member yang masuk ke grup tolong di perbaiki
Sekian terimakasih 🙏🏻
RAF#1
This user Your Bot Sc

**Comment by XM4ZE** [comment]
> Teruntuk developer bot ini saya ingin melaporkan bahwa fitur welcome tidak memunculkan thumbnail atau foto profil member yang masuk ke grup tolong di perbaiki Sekian terimakasih 🙏🏻 RAF#1 This user Your Bot Sc

![Screenshot_2024-07-23-10-46-32-794_com github android](https://github.com/user-attachments/assets/b741736a-d616-43e2-88f1-d6b02a4bffe9)
Untuk thumbnail kamu bisa tambahkan link thumbnail kamu di bagian global.maximus = 'https://yourlinkthub.jpg'
