### ISSUE TITLE
Tidak bisa di run

### ISSUE THREAD

**Issue by rafiadlifairuz** [XM4ZE/XMYULA-MD#6]
Tidak bisa di run
![IMG-20241002-WA0276](https://github.com/user-attachments/assets/89a44201-c14e-4bee-889f-5ef834274332)

**Comment by XM4ZE** [comment]
Gunakan script bot terbaru

**Comment by rafiadlifairuz** [comment]
Baik

Pada Rab, 2 Okt 2024 18.06, X ***@***.***> menulis:
